### ISSUE TITLE
Bug: unwanted addition of classical bits via `measure_all`

### ISSUE THREAD

**Issue by MattePalte** [tula3and/random-question-generator#12]
# Environment

- **qiskit.__version__**: 0.22.0
- **Python version**: 3.8.0
- **Operating system**: Ubuntu 20.04

# What is happening?
In the Python file [qrng.py](https://github.com/tula3and/random-question-generator/blob/main/qrng.py), the `measure_all` API call creates a new classical register even though the `circuit` already has a classical register of size `5`. This is due to the default behavior of `measure_all`, which always inserts a new register if not explicitly mentioned otherwise.

# How can we reproduce the issue?
Run the `random_number` function in the Python file:

```python
from qiskit import *

def random_number():
    qr = QuantumRegister(5)
    cr = ClassicalRegister(5)
    circuit = QuantumCircuit(qr,cr)
    circuit.h(qr)
    circuit.measure_all()
    print(circuit.draw())
    # backend = Aer.get_backend('qasm_simulator')
    # result = execute(circuit, backend, shots=1, memory=True).result()
    # counts = result.get_memory()
    # num = counts[0].split(" ")[0]
    # return int(num, 2)
random_number()
```
From the print statement, we can see that two circuits are present: `c` and `meas`. The first one is the one we created, the second one is the one created by `measure_all`.

# What should happen?
I would expect the existing classical register to be used instead to avoid waste of space.

# Any suggestions?
Following the documentation of the [`measure_all`](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.measure_all.html) method, it is possible to measure the qubits directly, without adding an extra register. The code should be changed to:

```python
circuit.measure_all(add_bits=False)
```

This will prevent the creation of an unnecessary classical register when one already exists.

**Comment by tula3and** [comment]
Thank you for finding the bug for this app! 😄
