### ISSUE TITLE
Add Arabic Language to your App 

### ISSUE THREAD

**Issue by ghost** [tula3and/random-question-generator#4]
Can I help  You With it

**Comment by tula3and** [comment]
Sure. Thanks for your suggestion! Just in case, I want to ask one thing. If some new questions are added, could you keep updating? I do not know Arabic so I am not sure that I can translate them correctly.

**Comment by ghost** [comment]
@tula3and  
 sure , I will definitely be always on the lookout for every update that happens, I would like to thank you for your trust and acceptance of me to participate in your project

**Comment by tula3and** [comment]
I've added Arabic language option to the app. You can check your translation from now! I also would like to request translating for one more question from #6. Thank you!
